### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by munierujp** [lazarljubenovic/type-guards#44]
type-guards is an indispensable library for writing type-safe codes.
However, the major version of it is still 0 and has not been updated for a long time.
Is this project still being maintained?

Thank you for creating awesome library.

**Comment by lazarljubenovic** [comment]
Glad you find the library useful. We use in production every day, and I don't see a reason why you'd refrain from using it because of the version number, considering it's a micro-utility-library and you can easily code-review any function you use.

I don't feel like releasing a 1.0.0 of it util I address the open issues (which are all mostly day-zero ideas which I never got around to implementing). It's very much alive, although certainly not on my priority list at the moment (busy with work!). If you have any ideas or requests, feel free to write.

**Comment by munierujp** [comment]
@lazarljubenovic It was good to know that this project is active.
Thank you for your reply.
